apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
  labels:
    app: reddit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit-app
        image: reddit-app:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  selector:
    app: reddit
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
